### ISSUE TITLE
Online Demo

### ISSUE THREAD

**Issue by stephen-hill** [skyronic/crudkit#1]
Hi

Do you have an online demo of what this application does?

Crudkit.com simply goes to a holding page.

Cheers
Stephen

**Comment by skyronic** [comment]
Wow, didn't expect anyone to even see this :)

It's going to be released in 2 weeks or so, and yes, there will be an online demo.

**Comment by stephen-hill** [comment]
There was a link in PHP weekly :)

**Comment by skyronic** [comment]
Hi Stephen,

The demo is now up on http://crudkit.com/ let me know what you think!

Thanks,
Anirudh
