### ISSUE TITLE
Utilize Interfaces for BaseDataProvider and BasePage

### ISSUE THREAD

**Issue by thepsion5** [skyronic/crudkit#31]
The current implementation of Data Providers and Pages is requires extending a base class, which is inflexible and makes extending and testing more difficult. A better approach is to create interfaces for both, and possibly replace the base classes with traits that have the same functionality. This will also allow for better usage of typehinting.

I'm interested in using this library at work but not having interfaces to work with would create additional maintenance liabilities for us, so I'm willing to create a PR with the required changes (and relevant tests, even!).

**Comment by skyronic** [comment]
Sure. Go right ahead. I would really appreciate more insight on how I can organize this better. I do forsee changing the interfaces a little bit in the near future though, maybe use a single function for validation and things like that.

I was planning to re-architect the pages to enable several use-cases:

1. Custom page infrastructure with their own controllers, templates, JS files and stylesheets.
2. Override the data providers to theoretically support additional non-sql databases so the basic CRUD UI and frontend can be preserved, but will apply to non-sql backends.

So are you talking about something like this:

```
IPage   -> BaseSQLPage (mixed in with DataPageTrait) -> MySQLPage
```

**Comment by thepsion5** [comment]
I've had some spare time to work on this recently (I'm currently snowed in) and extracted `BaseDataProvider` and `BasePage` into `DataProvider` and `Page` interfaces, respectively. I didn't add tests for either since I'd much prefer to do some refactoring first, since it would make testing much easier.

Expect a pull request shortly! Do you mind if I open another couple issues with refactoring in mind?
