### ISSUE TITLE
Installation via Composer -   SQL driver problem?

### ISSUE THREAD

**Issue by pentiumoverdrive** [skyronic/crudkit#44]
I just did a fresh install using:

> composer create-project skyronic/crudkit-template your_project

When I fire up the crudkit website (using this with apache2) with default crudkit settings I recieve the following:

Doctrine \ DBAL \ Exception \ DriverException
An exception occured in driver: could not find driver

[vhost]/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php
            return new Exception\ReadOnlyException($message, $exception);
        }

        if (strpos($exception->getMessage(), 'unable to open database file') !== false) {
            return new Exception\ConnectionException($message, $exception);
        }

        return new Exception\DriverException($message, $exception);
    }
 

Am I missing something or is the installation guide missing something?

The file html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php does exist.
I get the same error when trying to build an mysql page.
This is under Debian 8.2 without selinux.

Thanks!

**Comment by pentiumoverdrive** [comment]
This file does also exist in the default location:
-rwxrwxrwx  1 www-data www-data 1067008 Feb  2 09:43 demo_database.sqlite

**Comment by nishubawa** [comment]
sudo apt-get install php5-sqlite
sudo service apache2 restart

**Comment by skyronic** [comment]
Thank you, @nishubawa that is the right solution. 

@pentiumoverdrive you might also need https://packages.debian.org/squeeze/php5-mysql when you work with mysql...
