### ISSUE TITLE
Install w/o Node (and is this toolkit still alive)?

### ISSUE THREAD

**Issue by jasteele12** [skyronic/crudkit#72]
Just wondering if this can be built locally on windows w/o Grunt/Node?

28 Open issues and to Pull request since August 2016 - Is this toolkit still alive?

**Comment by skyronic** [comment]
@jasteele12 I haven't been able to give any time to this for the last few months. I don't intend to abandon this project, but at this point I advise against using this in production environments.

I would really like to improve some of the core concepts and change some architectural issues in a few months - making it easier to integrate and embed with Frameworks.
