### ISSUE TITLE
Add validation for inputs

### ISSUE THREAD

**Issue by skyronic** [skyronic/crudkit#8]

**Comment by pulse-sg** [comment]
would parsley.js be something to consider for this?

**Comment by skyronic** [comment]
Hi Aaron,

I will be validating it on server-side only for the beginning. The reason for this is that parsley will be able to validate client side but one of the rules I'm following is that even if someone has access to the system he can't be trusted completely and all inputs are validated for requirements, else it might lead to internal server errors (NULLs being inserted into NOT NULL columns, etc)

**Comment by skyronic** [comment]
Basic validation is now enabled in #22
